export const CREATE_POST = 'POSTS/CREATE_POST'
export const GET_ASYNC_POSTS = 'POSTS/GET_ASYNC_POSTS'

export const SHOW_LOADER = 'APP/SHOW_LOADER'
export const HIDE_LOADER = 'APP/HIDE_LOADER'

export const SHOW_ALERT = 'APP/SHOW_ALERT'
export const HIDE_ALERT = 'APP/HIDE_ALERT'

export const REQUEST_POSTS = 'POSTS/REQUEST_POSTS'
